name: CI/CD

on:
  push:
    branches: [ release ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: taehun2/bustracker:${{ github.ref_name }}
          build-args: |
            SPRING_PROFILES_ACTIVE=prod
            DATABASE_NAME=${{ secrets.DATABASE_NAME}}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}
            OAUTH_SECRET_KEY=${{ secrets.OAUTH_SECRET_KEY }}
            UNIV_API_KEY=${{ secrets.UNIV_API_KEY }}
            KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}

      - name: Trigger deployment
        run: |
          curl -X POST ${{ secrets.OFFICE_PC_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "image": "taehun2/bustracker:${{ github.ref_name }}",
            "env": {
              "SPRING_PROFILES_ACTIVE": "prod",
              "DATABASE_NAME": "${{ secrets.DATABASE_NAME}}",
              "MONGODB_URI": "${{ secrets.MONGODB_URI }}",
              "OAUTH_CLIENT_ID": "${{ secrets.OAUTH_CLIENT_ID }}",
              "OAUTH_SECRET_KEY": "${{ secrets.OAUTH_SECRET_KEY }}",
              "UNIV_API_KEY": "${{ secrets.UNIV_API_KEY }}",
              "KAKAO_REST_API_KEY": "${{ secrets.KAKAO_REST_API_KEY }}",
              "JWT_SECRET": "${{ secrets.JWT_SECRET }}"
            }
          }'